(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],workspace=$('#workspace'),row=$('#slideRow'),thumbs=$('#slideThumbs');
let slides=[],active=0,tool='select',locked=false,zoom=20,ratio='16/9',capturePadding=80,cameraStream=null,microphoneStream=null,cachedDisplayStream=null,cachedDisplayMode=null,recorder=null,chunks=[],teleTimer=null,telePaused=false,dragPan=null,recordTimer=null,audioContext=null,vadContext=null,vadFrame=null,neuralVad=null,neuralVadPromise=null,neuralSpeaking=false,lastVoiceAt=0,lastSpeechMatchAt=0,recordTracks=[],captureSession=null,videoCompositor=null;
const drawStyle={stroke:'#1d1d1f',fill:'transparent',width:4,dash:'solid',rough:1,opacity:1,font:'hand',fontSize:28,align:'left'};
let recordMode='studio';
/* === Rough.js integration === */
function roughCanvas(s){return rough.canvas(s.canvas)}
function drawWithRough(rc,a,b,type,style){
  const fill=style.fill==='transparent'?undefined:style.fill;
  const opts={
    stroke:style.stroke,strokeWidth:style.width,fill,fillStyle:'hachure',
    fillWeight:style.width*.6,hachureGap:style.width*2.5,
    roughness:style.rough===0?0:style.rough===1?1.4:2.6,
    bowing:style.rough===0?0:1,
    strokeLineDash:style.dash==='dashed'?[12,8]:style.dash==='dotted'?[2,8]:undefined
  };
  if(type==='rect')rc.rectangle(a.x,a.y,b.x-a.x,b.y-a.y,opts);
  else if(type==='circle'){const rx=Math.abs(b.x-a.x)/2,ry=Math.abs(b.y-a.y)/2;rc.ellipse(a.x+rx,a.y+ry,Math.max(1,Math.abs(b.x-a.x)),Math.max(1,Math.abs(b.y-a.y)),opts);}
  else if(type==='diamond'){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;rc.polygon([[mx,a.y],[b.x,my],[mx,b.y],[a.x,my]],opts);}
  else if(type==='line'||type==='arrow'){
    rc.line(a.x,a.y,b.x,b.y,opts);
    if(type==='arrow'){const ang=Math.atan2(b.y-a.y,b.x-a.x),len=Math.max(10,style.width*3);
      rc.line(b.x,b.y,b.x-len*Math.cos(ang-.5),b.y-len*Math.sin(ang-.5),{...opts,fill:undefined});
      rc.line(b.x,b.y,b.x-len*Math.cos(ang+.5),b.y-len*Math.sin(ang+.5),{...opts,fill:undefined});
    }
  }
}
/* === Smart tele toggle === */
const cameraHeading=$$('#settingsPanel h3').find(h=>h.textContent.trim()==='摄像头');
if(cameraHeading){cameraHeading.insertAdjacentHTML('beforebegin','<h3>录制模式</h3><div class="record-modes"><button data-record-mode="studio" class="active"><b>白板 + 摄像头</b><small>推荐选择当前标签页</small></button><button data-record-mode="screen"><b>屏幕 + 摄像头</b><small>共享屏幕或窗口</small></button><button data-record-mode="camera"><b>仅摄像头</b><small>直接录制相机与麦克风</small></button></div><div class="device-status" id="deviceStatus"><i></i><span>点击"开启摄像头"进行设备自检</span></div>')}
const teleTextarea=$('#script');
if(teleTextarea){teleTextarea.insertAdjacentHTML('afterend','<div class="smart-tele-row"><button class="toggle active" id="smartTeleToggle"><i></i></button><div><b>智能跟读</b><small>根据你的实际语速自动定位，停顿时提词也停下</small></div><span id="listenState">待机</span></div>')}
const endSessionBtn=document.createElement('button');endSessionBtn.id='endSessionBtn';endSessionBtn.className='end-session-btn';endSessionBtn.textContent='结束共享';endSessionBtn.hidden=true;$('#recordBtn').parentNode.insertBefore(endSessionBtn,$('#recordBtn'));
const statusToast=document.createElement('div');statusToast.className='status-toast';statusToast.setAttribute('role','status');$('#studio').appendChild(statusToast);let toastTimer=null;
function showToast(message,type=''){clearTimeout(toastTimer);statusToast.textContent=message;statusToast.className='status-toast show '+type;toastTimer=setTimeout(()=>statusToast.classList.remove('show'),2400)}
const uid=()=>Math.random().toString(36).slice(2,9),current=()=>slides[active],canvas=()=>current().canvas,ctx=()=>current().ctx;
$('#canvasPadding').addEventListener('input',e=>{capturePadding=+e.target.value;$('#paddingOut').value=capturePadding+'px';if(captureSession)sizeCaptureStage()});
$$('[data-record-mode]').forEach(b=>b.addEventListener('click',()=>{if(captureSession)resetRecordButton()}));
$$('.ratio').forEach(b=>b.addEventListener('click',()=>requestAnimationFrame(()=>{if(captureSession)sizeCaptureStage()})));
function safeTelePosition(left,top,width,height){left=Math.max(0,Math.min(innerWidth-width,left));top=Math.max(0,Math.min(innerHeight-height,top));if(!captureSession)return{left,top};const s=captureSession.stage.getBoundingClientRect(),gap=12,overlaps=left<s.right+gap&&left+width>s.left-gap&&top<s.bottom+gap&&top+height>s.top-gap;if(!overlaps)return{left,top};const options=[{left,top:s.top-height-gap},{left,top:s.bottom+gap},{left:s.left-width-gap,top},{left:s.right+gap,top}].map(p=>({left:Math.max(0,Math.min(innerWidth-width,p.left)),top:Math.max(0,Math.min(innerHeight-height,p.top))})).filter(p=>p.left+width<=s.left-gap||p.left>=s.right+gap||p.top+height<=s.top-gap||p.top>=s.bottom+gap);if(!options.length)return{left,top:Math.max(0,Math.min(innerHeight-height,s.bottom+gap))};return options.sort((a,b)=>(a.left-left)**2+(a.top-top)**2-(b.left-left)**2-(b.top-top)**2)[0]}
function keepTeleOutsideCapture(){const tele=$('#teleprompter');if(!captureSession||!tele.classList.contains('show'))return;const r=tele.getBoundingClientRect(),p=safeTelePosition(r.left,r.top,r.width,r.height);tele.style.left=p.left+'px';tele.style.top=p.top+'px';tele.style.right='auto';tele.style.bottom='auto';tele.style.transform='none'}
function makeDraggable(el,key){let drag=null;const movedTransform=el.id==='camera'?'scaleX(-1)':'none',saved=localStorage.getItem(key);if(saved){try{const p=JSON.parse(saved);el.style.left=p.left+'px';el.style.top=p.top+'px';el.style.right='auto';el.style.bottom='auto';el.style.transform=movedTransform}catch(e){}}el.addEventListener('pointerdown',e=>{if(e.target.closest('button,input,textarea,select')||e.button!==0)return;const r=el.getBoundingClientRect(),pr=el.offsetParent?.getBoundingClientRect()||{left:0,top:0,width:innerWidth,height:innerHeight};drag={x:e.clientX,y:e.clientY,left:r.left-pr.left,top:r.top-pr.top,parent:pr};el.setPointerCapture(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!drag)return;let left=Math.max(0,Math.min(drag.parent.width-el.offsetWidth,drag.left+e.clientX-drag.x)),top=Math.max(0,Math.min(drag.parent.height-el.offsetHeight,drag.top+e.clientY-drag.y));if(el.id==='teleprompter'&&captureSession)({left,top}=safeTelePosition(left,top,el.offsetWidth,el.offsetHeight));el.style.left=left+'px';el.style.top=top+'px';el.style.right='auto';el.style.bottom='auto';el.style.transform=movedTransform});el.addEventListener('pointerup',()=>{if(!drag)return;localStorage.setItem(key,JSON.stringify({left:parseFloat(el.style.left),top:parseFloat(el.style.top)}));drag=null;el.classList.remove('dragging')})}
function makeSlide(){return{id:uid(),canvas:null,ctx:null,card:null,undo:[],redo:[],bg:'#fff',template:'',media:[]}}
function buildSlide(slide,index){const card=document.createElement('article');card.className='slide-card'+(index===active?' selected':'');card.dataset.index=index;card.innerHTML=`<label>Slide ${index+1}</label><div class="slide-frame"><div class="template-layer"></div><div class="media-layer"></div><canvas class="draw-canvas"></canvas><div class="empty-hint"><div><b>Slide ${index+1}</b>选择工具开始创作</div></div></div>`;row.appendChild(card);slide.card=card;slide.canvas=card.querySelector('canvas');slide.ctx=slide.canvas.getContext('2d');fitCanvas(slide);attachCanvas(slide);card.addEventListener('pointerdown',()=>selectSlide(index,false));}
function fitCanvas(s){const c=s.canvas,w=c.clientWidth,h=c.clientHeight,old=c.width?c.toDataURL():null;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;s.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);s.ctx.lineCap='round';s.ctx.lineJoin='round';if(old){const im=new Image;im.onload=()=>s.ctx.drawImage(im,0,0,w,h);im.src=old}}
function renderAll(){row.innerHTML='';slides.forEach(buildSlide);renderThumbs();requestAnimationFrame(()=>slides.forEach(fitCanvas))}
function renderThumbs(){thumbs.innerHTML='';slides.forEach((s,i)=>{const b=document.createElement('button');b.className='thumb'+(i===active?' active':'');b.textContent=i+1;b.title=`切换到幻灯片 ${i+1}`;b.onclick=()=>selectSlide(i,true);thumbs.appendChild(b)})}
function selectSlide(i,scroll=true){active=i;$$('.slide-card').forEach((c,n)=>c.classList.toggle('selected',n===i));$$('.thumb').forEach((b,n)=>b.classList.toggle('active',n===i));if(captureSession)switchCaptureSlide(i);else if(scroll)slides[i].card.scrollIntoView({behavior:'smooth',block:'center',inline:'center'})}
function snapshot(s=current()){return s.canvas.toDataURL()}function push(s=current()){s.undo.push(snapshot(s));if(s.undo.length>50)s.undo.shift();s.redo=[];const hint=s.canvas.closest('.slide-frame')?.querySelector('.empty-hint')||s.card.querySelector('.empty-hint');if(hint)hint.style.display='none'}
function restore(s,url){s.ctx.clearRect(0,0,s.canvas.width,s.canvas.height);if(!url)return;const im=new Image;im.onload=()=>s.ctx.drawImage(im,0,0,s.canvas.clientWidth,s.canvas.clientHeight);im.src=url}
function point(e,c){const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function frameOf(s=current()){return s.canvas.closest('.slide-frame')||s.card.querySelector('.slide-frame')}
function mediaLayerOf(s=current()){return frameOf(s)?.querySelector('.media-layer')}
function hideEmptyHint(s=current()){const hint=frameOf(s)?.querySelector('.empty-hint');if(hint)hint.style.display='none'}
function beginTextEditor(s,p){const frame=frameOf(s),editor=document.createElement('textarea');editor.className='canvas-text-editor';editor.placeholder='输入文字…';editor.style.left=p.x+'px';editor.style.top=p.y+'px';editor.style.color=drawStyle.stroke;editor.style.fontSize=drawStyle.fontSize+'px';editor.style.fontFamily=drawStyle.font==='hand'?'KaiTi':drawStyle.font==='serif'?'Georgia':'Arial';editor.style.textAlign=drawStyle.align;frame.appendChild(editor);editor.focus();let cancelled=false,finished=false;const commit=()=>{if(finished)return;finished=true;try{const text=editor.value.trim();if(text&&!cancelled){const item=document.createElement('div');item.className='media-item text-item selected';item.textContent=text;item.style.left=p.x+'px';item.style.top=p.y+'px';item.style.transform='none';item.style.color=drawStyle.stroke;item.style.fontSize=drawStyle.fontSize+'px';item.style.fontFamily=drawStyle.font==='hand'?'KaiTi':drawStyle.font==='serif'?'Georgia':'Arial';item.style.textAlign=drawStyle.align;item.style.opacity=drawStyle.opacity;mediaLayerOf(s).appendChild(item);makeMediaInteractive(item);hideEmptyHint(s);if(!locked)setTimeout(()=>setTool('select'));showToast('文字已创建 · 可拖动，双击可编辑')}}finally{editor.remove()}};editor.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelled=true;commit()}if((e.metaKey||e.ctrlKey)&&e.key==='Enter')commit()});editor.addEventListener('blur',commit,{once:true})}
/* === Canvas drawing with rough.js === */
function attachCanvas(s){
  let drawing=false,start=null,buffer=null,bufferCtx=null;
  const c=s.canvas,x=s.ctx,rc=roughCanvas(s);
  c.onpointerdown=e=>{
    if(tool==='select'||tool==='hand')return;e.preventDefault();selectSlide(slides.indexOf(s),false);start=point(e,c);
    if(tool==='text'){beginTextEditor(s,start);return}
    buffer=document.createElement('canvas');buffer.width=c.width;buffer.height=c.height;bufferCtx=buffer.getContext('2d');bufferCtx.drawImage(c,0,0);push(s);drawing=true;
    if(tool==='pen'||tool==='eraser'){x.save();applyDrawStyle(x);x.lineWidth=tool==='eraser'?22:drawStyle.width;x.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';x.beginPath();x.moveTo(start.x,start.y);c.setPointerCapture(e.pointerId)}
  };
  c.onpointermove=e=>{
    if(!drawing)return;const p=point(e,c);
    if(tool==='pen'||tool==='eraser'){x.lineTo(p.x,p.y);x.stroke();return}
    // Preview: clear and redraw from buffer + rough shape
    x.save();x.setTransform(1,0,0,1,0,0);x.clearRect(0,0,c.width,c.height);x.drawImage(buffer,0,0);x.restore();
    drawWithRough(rc,start,p,tool,drawStyle);
  };
  c.onpointerup=()=>{if(drawing){drawing=false;buffer=null;bufferCtx=null}}
}
function applyDrawStyle(x){x.strokeStyle=drawStyle.stroke;x.fillStyle=drawStyle.fill;x.lineWidth=drawStyle.width;x.globalAlpha=drawStyle.opacity;x.setLineDash(drawStyle.dash==='dashed'?[12,8]:drawStyle.dash==='dotted'?[2,8]:[])}
function setTool(t){$('.canvas-text-editor')?.blur();tool=t;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));workspace.classList.toggle('hand',t==='hand');const styled=!['select','hand','eraser'].includes(t);$('#stylePanel').classList.toggle('open',styled);$('#styleTitle').textContent=t==='text'?'文字样式':t==='pen'?'画笔样式':'元素样式';$('#fillSection').style.display=['rect','diamond','circle'].includes(t)?'block':'none';$('#textOptions').style.display=t==='text'?'block':'none'}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#lockBtn').onclick=()=>{locked=!locked;$('#lockBtn').classList.toggle('locked',locked);showToast(locked?'已锁定工具':'已解锁工具')};
$('#closeStyle').onclick=()=>$('#stylePanel').classList.remove('open');function activateChoice(selector,el){$$(selector).forEach(x=>x.classList.toggle('active',x===el))}$$('[data-stroke]').forEach(b=>b.onclick=()=>{drawStyle.stroke=b.dataset.stroke;activateChoice('[data-stroke]',b)});$('#customStroke').oninput=e=>drawStyle.stroke=e.target.value;$$('[data-fill]').forEach(b=>b.onclick=()=>{drawStyle.fill=b.dataset.fill;activateChoice('[data-fill]',b)});$$('[data-width]').forEach(b=>b.onclick=()=>{drawStyle.width=+b.dataset.width;activateChoice('[data-width]',b)});$$('[data-dash]').forEach(b=>b.onclick=()=>{drawStyle.dash=b.dataset.dash;activateChoice('[data-dash]',b)});$$('[data-rough]').forEach(b=>b.onclick=()=>{drawStyle.rough=+b.dataset.rough;activateChoice('[data-rough]',b);showToast(b.textContent==='精准'?'精准线条':b.textContent==='自然'?'自然手绘':'手绘风格')});$$('[data-font]').forEach(b=>b.onclick=()=>{drawStyle.font=b.dataset.font;activateChoice('[data-font]',b)});$$('[data-font-size]').forEach(b=>b.onclick=()=>{drawStyle.fontSize=+b.dataset.fontSize;activateChoice('[data-font-size]',b)});$$('[data-align]').forEach(b=>b.onclick=()=>{drawStyle.align=b.dataset.align;activateChoice('[data-align]',b)});$('#opacity').oninput=e=>{drawStyle.opacity=e.target.value/100;$('#opacityOut').value=e.target.value};$$('[data-layer]').forEach(b=>b.onclick=()=>{const el=$('.media-item.selected');if(!el)return;const z=+(el.style.zIndex||1),a=b.dataset.layer;el.style.zIndex=a==='front'?99:a==='back'?0:a==='up'?z+1:Math.max(0,z-1)});
$('#addSlide').onclick=()=>{const s=makeSlide();slides.push(s);buildSlide(s,slides.length-1);renderThumbs();selectSlide(slides.length-1,true);showToast('新幻灯片已创建')};
/* === Export functions === */
function exportPNG(){const c=current().canvas;const link=document.createElement('a');link.download=`rhino-whiteboard-${Date.now()}.png`;link.href=c.toDataURL('image/png');link.click();showToast('PNG 已导出')}
function exportJSON(){const data=slides.map(s=>({id:s.id,image:s.canvas.toDataURL(),media:s.media,template:s.template,bg:s.bg}));const blob=new Blob([JSON.stringify(data)],{type:'application/json'});const link=document.createElement('a');link.download=`rhino-whiteboard-${Date.now()}.json`;link.href=URL.createObjectURL(blob);link.click();setTimeout(()=>URL.revokeObjectURL(link.href),5000);showToast('JSON 已导出')}
$('#exportBtn').onclick=()=>{const choice=confirm('确定导出为 PNG？\n\n点击"确定"导出 PNG\n点击"取消"导出 JSON 工程');if(choice)exportPNG();else exportJSON()};
$('#undo').onclick=()=>{const s=current();if(!s.undo.length){showToast('没有可撤销的操作');return}s.redo.push(snapshot(s));restore(s,s.undo.pop());showToast('已撤销')};
$('#redo').onclick=()=>{const s=current();if(!s.redo.length){showToast('没有可重做的操作');return}s.redo.push(snapshot(s));restore(s,s.redo.pop());showToast('已重做')};
workspace.onpointerdown=e=>{if(tool!=='hand')return;dragPan={x:e.clientX,y:e.clientY,l:workspace.scrollLeft,t:workspace.scrollTop};workspace.classList.add('dragging')};workspace.onpointermove=e=>{if(!dragPan)return;workspace.scrollLeft=dragPan.l-(e.clientX-dragPan.x);workspace.scrollTop=dragPan.t-(e.clientY-dragPan.y)};workspace.onpointerup=()=>{dragPan=null;workspace.classList.remove('dragging')};
function setZoom(n){zoom=Math.max(10,Math.min(100,n));row.style.transform=`scale(${zoom/20})`;row.style.transformOrigin='top left';$('#zoomValue').textContent=zoom+'%'}$('#zoomOut').onclick=()=>setZoom(zoom-5);$('#zoomIn').onclick=()=>setZoom(zoom+5);
$('#moreBtn').onclick=e=>{e.stopPropagation();$('#moreMenu').classList.toggle('open')};document.addEventListener('click',e=>{if(!e.target.closest('#moreMenu')&&!e.target.closest('#moreBtn'))$('#moreMenu').classList.remove('open')});
function insertFile(kind,file){const s=current(),layer=mediaLayerOf(s);if(!layer||!file){showToast('当前画布尚未准备好','error');return}const url=URL.createObjectURL(file),el=document.createElement(kind==='image'?'img':'video');el.src=url;el.className='media-item';if(kind==='video'){el.controls=true;el.playsInline=true;el.preload='metadata';el.addEventListener('loadedmetadata',()=>{setDeviceStatus('ready',`视频已插入 · ${Math.round(el.duration||0)} 秒`);showToast(`视频已插入 · ${Math.round(el.duration||0)} 秒`)},{once:true});el.addEventListener('error',()=>{setDeviceStatus('error','视频无法解码，请使用 MP4（H.264）或 WebM');showToast('视频无法解码，请换用 H.264 MP4','error')},{once:true})}else el.addEventListener('load',()=>showToast('图片已插入'),{once:true});layer.appendChild(el);makeMediaInteractive(el);s.media.push({kind,url});hideEmptyHint(s);$$('.media-item').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');if(!locked)setTool('select')}
function makeMediaInteractive(el){el.onclick=e=>{e.stopPropagation();$$('.media-item').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')};if(el.classList.contains('text-item')){el.title='单击选中，双击编辑文字';el.ondblclick=e=>{e.stopPropagation();el.contentEditable='true';el.classList.add('editing');el.focus();const range=document.createRange(),sel=getSelection();range.selectNodeContents(el);range.collapse(false);sel.removeAllRanges();sel.addRange(range)};el.addEventListener('blur',()=>{el.contentEditable='false';el.classList.remove('editing')})}let d=null;el.onpointerdown=e=>{if(tool!=='select'||el.isContentEditable)return;d={x:e.clientX,y:e.clientY,l:el.offsetLeft,t:el.offsetTop};el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!d)return;el.style.left=d.l+e.clientX-d.x+'px';el.style.top=d.t+e.clientY-d.y+'px';el.style.transform='none'};el.onpointerup=()=>d=null}
$('#imageInput').onchange=e=>{const f=e.target.files[0];if(f)insertFile('image',f);e.target.value=''};$('#videoInput').onchange=e=>{const f=e.target.files[0];if(f)insertFile('video',f);e.target.value=''};$('#imageTool').onclick=()=>$('#imageInput').click();
$$('[data-insert]').forEach(b=>b.onclick=()=>{const k=b.dataset.insert;$('#moreMenu').classList.remove('open');if(k==='image')$('#imageInput').click();if(k==='video')$('#videoInput').click();if(k==='template')openPanel('templatePanel');if(k==='sticky'){const note=document.createElement('textarea');note.className='sticky-note media-item';note.value='记录一个好想法…';mediaLayerOf().appendChild(note);makeMediaInteractive(note);hideEmptyHint()}if(k==='grid'){const f=frameOf(),m=['','grid-dots','grid-lines','grid-square'],i=m.findIndex(x=>x&&f.classList.contains(x));f.classList.remove(...m.filter(Boolean));f.classList.add(m[(i+1)%m.length]||'grid-dots')}if(k==='focus'){$('#studio').classList.toggle('focus-mode')}if(k==='web'){const u=prompt('输入要嵌入的网页地址（需支持 iframe）：','https://');if(!u)return;const f=document.createElement('iframe');f.src=u;f.className='media-item web';f.setAttribute('sandbox','allow-scripts allow-same-origin allow-forms allow-popups');mediaLayerOf().appendChild(f);makeMediaInteractive(f);hideEmptyHint()}});
function openPanel(id){$$('.panel').forEach(p=>p.classList.toggle('open',p.id===id))}$('#settingsBtn').onclick=()=>openPanel('settingsPanel');$('#scriptBtn').onclick=()=>openPanel('scriptPanel');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));
$$('.ratio').forEach(b=>b.onclick=()=>{ratio=b.dataset.ratio==='custom'?(prompt('输入自定义比例，例如 5/4','5/4')||'16/9'):b.dataset.ratio;$$('.ratio').forEach(x=>x.classList.toggle('active',x===b));$$('.slide-frame').forEach(f=>f.style.aspectRatio=ratio);$('#recordPreview').style.aspectRatio=ratio;setTimeout(()=>slides.forEach(fitCanvas),80)});$$('[data-bg]').forEach(b=>b.onclick=()=>{const s=current();s.bg=b.dataset.bg;frameOf(s).style.background=b.dataset.bg});
const wallpapers=$$('[data-wallpaper]');function applyWallpaper(value,button){$('#recordPreview').style.background=value;$('#studio').style.background=value;wallpapers.forEach(x=>x.classList.toggle('active',x===button))}wallpapers.forEach(b=>b.onclick=()=>applyWallpaper(b.dataset.wallpaper,b));$('#randomWallpaper').onclick=()=>{const b=wallpapers[Math.floor(Math.random()*wallpapers.length)];applyWallpaper(b.dataset.wallpaper,b)};$('#canvasRadius').oninput=e=>{$('#radiusOut').value=e.target.value+'px';$$('.slide-frame').forEach(f=>f.style.borderRadius=e.target.value+'px');$('#recordPreview').style.borderRadius=e.target.value+'px'};$('#cameraSize').oninput=e=>{cam.style.width=e.target.value+'px';$('#cameraSizeOut').value=e.target.value+'px'};$$('[data-camera-shape]').forEach(b=>b.onclick=()=>{cam.style.borderRadius=b.dataset.cameraShape;$$('[data-camera-shape]').forEach(x=>x.classList.toggle('active',x===b))});$('#canvasPadding').oninput=e=>{workspace.style.paddingLeft=e.target.value+'px';workspace.style.paddingRight=e.target.value+'px';$('#paddingOut').value=e.target.value+'px'};$('#cameraToggle').onclick=()=>{$('#cameraToggle').classList.toggle('active');cam.classList.toggle('show',$('#cameraToggle').classList.contains('active')&&!!cameraStream)};$('#cursorToggle').onclick=()=>{$('#cursorToggle').classList.toggle('active');$('#cursorSpot').classList.toggle('show',$('#cursorToggle').classList.contains('active'))};$$('[data-cursor]').forEach(b=>b.onclick=()=>{$('#cursorSpot').style.borderColor=b.dataset.cursor;$('#cursorSpot').style.boxShadow=`0 0 0 8px ${b.dataset.cursor}2a`;$$('[data-cursor]').forEach(x=>x.classList.toggle('active',x===b))});addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--focus-x',e.clientX+'px');document.documentElement.style.setProperty('--focus-y',e.clientY+'px');$('#cursorSpot').style.left=e.clientX+'px';$('#cursorSpot').style.top=e.clientY+'px'});
const templates={title:`<div style="height:100%;padding:11%;background:linear-gradient(135deg,#fff8ef,#edf4ff);display:flex;flex-direction:column;justify-content:center"><small style="letter-spacing:.2em;color:#806f60">RHINO STUDIO</small><h1 style="font:700 48px Georgia;margin:12px 0">在此输入标题</h1><p style="font-size:20px;color:#777">用一句话说明你的核心观点</p></div>`,lesson:`<div style="height:100%;display:grid;grid-template-columns:30% 1fr"><div style="background:#20242d;color:#fff;padding:14%"><b>01</b><h2 style="font:32px Georgia">课程主题</h2></div><div style="padding:9%"><h1>今天我们讲什么？</h1><p style="color:#777;font-size:18px">在右侧画布逐步拆解你的内容</p></div></div>`,points:`<div style="height:100%;padding:8%;background:#fcfaf5"><h1 style="font:38px Georgia">三个关键要点</h1><div style="display:flex;gap:4%;margin-top:8%">${[1,2,3].map(n=>`<div style="flex:1;padding:5%;background:#fff;border-radius:12px"><b>0${n}</b><h2>要点 ${n}</h2><p style="color:#888">补充说明</p></div>`).join('')}</div></div>`,dark:`<div style="height:100%;padding:10%;color:#fff;background:radial-gradient(circle at 75% 25%,#4b59c4,#111521 58%)"><small style="color:#aab2ff">NEW IDEA</small><h1 style="font:700 52px Georgia;max-width:70%">让想法被看见</h1><p style="font-size:20px;color:#c7cae8">犀牛白板 · 创作发布会</p></div>`};$$('[data-template]').forEach(b=>b.onclick=()=>{const s=current();s.template=b.dataset.template;frameOf(s).querySelector('.template-layer').innerHTML=templates[s.template];hideEmptyHint(s);$('#templatePanel').classList.remove('open');showToast('模板已应用')});
$$('[data-record-mode]').forEach(b=>b.onclick=()=>{recordMode=b.dataset.recordMode;$$('[data-record-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#deviceStatus span').textContent=recordMode==='camera'?'将直接录制摄像头与麦克风':'录制时请在共享窗口中选择当前白板标签页'});
const cam=$('#camera');function setDeviceStatus(type,text){const s=$('#deviceStatus');if(!s)return;s.className='device-status '+type;s.querySelector('span').textContent=text}async function ensureCamera(){if(cameraStream&&cameraStream.getVideoTracks().some(t=>t.readyState==='live'))return cameraStream;if(!navigator.mediaDevices?.getUserMedia)throw new Error('浏览器不支持摄像头访问');cameraStream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30},facingMode:'user'},audio:false});cam.srcObject=cameraStream;await cam.play().catch(()=>{});cam.classList.toggle('show',$('#cameraToggle').classList.contains('active'));$('#cameraBtn').textContent='关闭摄像头';setDeviceStatus('ready','摄像头已就绪，可开始录制');return cameraStream}async function stopCamera(){if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;cam.srcObject=null;cam.classList.remove('show');$('#cameraBtn').textContent='开启摄像头';setDeviceStatus('','摄像头已关闭')}$('#cameraBtn').onclick=async()=>{if(cameraStream){await stopCamera();return}try{await ensureCamera();$('#cameraToggle').classList.add('active');cam.classList.add('show');showToast('摄像头已开启')}catch(e){setDeviceStatus('error',e?.name==='NotAllowedError'?'摄像头权限被拒绝，请在浏览器地址栏中允许':'摄像头启动失败：'+(e?.message||'未知错误'));showToast('摄像头启动失败','error')}};
function streamIsLive(stream,type){return !!stream&&stream.getTracks().some(t=>t.kind===type&&t.readyState==='live')}
async function startVoiceActivity(stream){if(!streamIsLive(stream,'audio'))return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(vadFrame)cancelAnimationFrame(vadFrame);if(vadContext)vadContext.close().catch(()=>{});vadContext=new AC();await vadContext.resume().catch(()=>{});const analyser=vadContext.createAnalyser(),source=vadContext.createMediaStreamSource(stream),data=new Uint8Array(512);let noiseFloor=.004;analyser.fftSize=1024;analyser.smoothingTimeConstant=.58;source.connect(analyser);const sample=()=>{analyser.getByteTimeDomainData(data);let sum=0;for(const value of data){const n=(value-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length),threshold=Math.max(.006,noiseFloor*1.75);if(rms>threshold){lastVoiceAt=Date.now();const state=$('#listenState');if(state&&smartTele&&!telePaused)state.textContent='已检测到语音，正在识别'}else noiseFloor=noiseFloor*.985+rms*.015;vadFrame=requestAnimationFrame(sample)};sample()}
function loadScriptOnce(src,id){return new Promise((resolve,reject)=>{const old=document.getElementById(id);if(old){if(old.dataset.ready==='1')resolve();else{old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true})}return}const script=document.createElement('script');script.id=id;script.src=src;script.async=true;script.onload=()=>{script.dataset.ready='1';resolve()};script.onerror=reject;document.head.appendChild(script)})}
async function startNeuralVad(stream){if(neuralVad){await neuralVad.start();return}if(neuralVadPromise)return neuralVadPromise;neuralVadPromise=(async()=>{await loadScriptOnce('https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/ort.wasm.min.js','rhino-ort');await loadScriptOnce('https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.29/dist/bundle.min.js','rhino-vad');if(!window.vad?.MicVAD)throw new Error('VAD 未加载');neuralVad=await window.vad.MicVAD.new({getStream:async()=>stream,onnxWASMBasePath:'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/',baseAssetPath:'https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.29/dist/',model:'v5',positiveSpeechThreshold:.3,negativeSpeechThreshold:.22,redemptionMs:700,minSpeechMs:160,preSpeechPadMs:120,onSpeechStart:()=>{neuralSpeaking=true;lastVoiceAt=Date.now();$('#listenState').textContent='已检测到语音，正在识别'},onSpeechEnd:()=>{neuralSpeaking=false;$('#listenState').textContent='已停顿，等待继续'},onVADMisfire:()=>{neuralSpeaking=false},onFrameProcessed:probs=>{if(probs?.isSpeech>.3){neuralSpeaking=true;lastVoiceAt=Date.now()}}});await neuralVad.start();$('#listenState').textContent='逐字识别已就绪'})().catch(e=>{$('#listenState').textContent='语音活动检测已启用，等待文字识别';neuralVadPromise=null;throw e});return neuralVadPromise}
async function ensureMicrophone(){if(streamIsLive(microphoneStream,'audio'))return microphoneStream;microphoneStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});startVoiceActivity(microphoneStream);endSessionBtn.hidden=false;return microphoneStream}
async function ensureDisplayStream(mode){if(streamIsLive(cachedDisplayStream,'video')&&cachedDisplayMode===mode)return cachedDisplayStream;if(cachedDisplayStream)cachedDisplayStream.getTracks().forEach(t=>t.stop());cachedDisplayStream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30,max:60},displaySurface:mode==='studio'?'browser':'monitor'},audio:true,preferCurrentTab:mode==='studio',selfBrowserSurface:'include',surfaceSwitching:'include'});cachedDisplayMode=mode;endSessionBtn.hidden=false;cachedDisplayStream.getVideoTracks()[0].addEventListener('ended',()=>{cachedDisplayStream=null;cachedDisplayMode=null;if(recorder?.state==='recording')stopRecording();endSessionBtn.hidden=!streamIsLive(microphoneStream,'audio')&&!streamIsLive(cameraStream,'video')},{once:true});return cachedDisplayStream}
function endMediaSession(){if(recorder?.state==='recording')stopRecording();[cachedDisplayStream,microphoneStream,cameraStream].forEach(s=>s?.getTracks().forEach(t=>t.stop()));cachedDisplayStream=null;cachedDisplayMode=null;microphoneStream=null;cameraStream=null;cam.srcObject=null;cam.classList.remove('show');if(neuralVad)Promise.resolve(neuralVad.pause()).catch(()=>{});neuralVad=null;neuralVadPromise=null;neuralSpeaking=false;if(vadFrame)cancelAnimationFrame(vadFrame);vadFrame=null;if(vadContext)vadContext.close().catch(()=>{});vadContext=null;endSessionBtn.hidden=true;setDeviceStatus('','创作会话已结束')}endSessionBtn.onclick=endMediaSession;addEventListener('beforeunload',endMediaSession);
makeDraggable(cam,'rhino-camera-position');makeDraggable($('#teleprompter'),'rhino-tele-position');if(window.ResizeObserver)new ResizeObserver(()=>{if(captureSession)requestAnimationFrame(keepTeleOutsideCapture)}).observe($('#teleprompter'));addEventListener('resize',()=>{if(captureSession)requestAnimationFrame(sizeCaptureStage)});
let speechRecognition=null,speechRestartTimer=null,speechRecognitionBlocked=false,speechCursor=0,speechCursorFloat=0,teleScriptNormalized='',teleSentenceEnds=[],teleSentences=[],teleSentenceIndex=0,smartTele=true;
function escapeTeleChar(c){return c.replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}
function updateTele(){const text=$('#script').value.trim()||'请先输入讲稿';teleSentences=text.match(/[^。！？!?\n]+[。！？!?]?/g)||[text];teleSentenceEnds=[];teleScriptNormalized='';let charIndex=0;const markup=teleSentences.map((s,i)=>{let chars='';for(const c of Array.from(s)){const normalized=normalizeSpeech(c);if(normalized){charIndex+=normalized.length;chars+=`<span class="tele-char" data-char="${charIndex}">${escapeTeleChar(c)}</span>`}else chars+=`<span class="tele-punct">${escapeTeleChar(c)}</span>`}teleScriptNormalized+=normalizeSpeech(s);teleSentenceEnds.push(teleScriptNormalized.length);return `<span class="tele-sentence${i===0?' active':''}" data-sentence="${i}">${chars}</span>`}).join('');speechCursor=0;speechCursorFloat=0;$('#teleText').innerHTML=markup;$('#teleText').style.fontSize=$('#fontSize').value+'px';$('#teleText').dataset.y=0;localStorage.setItem('rhino-tele-script',$('#script').value);teleSentenceIndex=0;setTeleProgress(0)}
function setTeleSentence(i){teleSentenceIndex=Math.max(0,Math.min(teleSentences.length-1,i));$$('.tele-sentence').forEach((s,n)=>s.classList.toggle('active',n===teleSentenceIndex))}
function setTeleProgress(position){const cursor=Math.max(0,Math.min(teleScriptNormalized.length,Math.floor(position))),currentIndex=Math.max(1,cursor);let current=null;$$('.tele-char').forEach(el=>{const index=+el.dataset.char,distance=cursor-index;el.classList.toggle('read',index<cursor);el.classList.toggle('current',index===currentIndex);if(index===currentIndex)current=el;if(distance>=0&&distance<10){const t=1-distance/10,r=Math.round(98+157*t),g=Math.round(205+10*t),b=Math.round(145-55*t);el.style.color=`rgb(${r},${g},${b})`}else el.style.color=''});const sentenceAt=teleSentenceEnds.findIndex(end=>cursor<=end),sentence=sentenceAt<0?teleSentences.length-1:sentenceAt;if(sentence!==teleSentenceIndex)setTeleSentence(sentence);if(current){const box=$('#teleprompter'),text=$('#teleText'),target=Math.min(0,box.clientHeight*.43-current.offsetTop-current.offsetHeight/2),previous=Number(text.dataset.y||0),y=Math.min(previous,target);if(y!==previous){text.dataset.y=y;text.style.transform=`translateY(${y}px)`}}}
function normalizeSpeech(s){return String(s).toLowerCase().replace(/[\s，。！？、,.!?：:；;""\"'（）()]/g,'')}
function editDistance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const previous=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,diagonal+(a[i-1]===b[j-1]?0:1));diagonal=previous}}return row[b.length]}
function fuzzySpeechPosition(spoken){const heard=spoken.slice(-28),start=Math.max(0,speechCursor-8),end=Math.min(teleScriptNormalized.length,speechCursor+Math.max(72,heard.length*4));let best={score:0,end:-1};for(let length=Math.min(heard.length,24);length>=3;length--){const phrase=heard.slice(-length);for(let position=Math.max(start+3,speechCursor);position<=end;position++){for(let delta=-2;delta<=2;delta++){const scriptLength=length+delta,from=position-scriptLength;if(scriptLength<3||from<start)continue;const sample=teleScriptNormalized.slice(from,position),score=1-editDistance(phrase,sample)/Math.max(phrase.length,sample.length);if(score>best.score||(score===best.score&&position<best.end))best={score,end:position}}}if(best.score>=.62)return best.end}return-1}
function followRecognizedText(heard){const spoken=normalizeSpeech(heard);if(spoken.length<2||!teleScriptNormalized)return false;const windowStart=Math.max(0,speechCursor-18),windowEnd=Math.min(teleScriptNormalized.length,speechCursor+220),windowText=teleScriptNormalized.slice(windowStart,windowEnd);let found=-1,matched=0;for(let len=Math.min(24,spoken.length);len>=2;len--){const phrase=spoken.slice(-len),at=windowText.lastIndexOf(phrase);if(at>=0){found=windowStart+at+len;matched=len;break}}if(found<0){found=fuzzySpeechPosition(spoken);matched=found>=0?3:0}if(found<0)return false;speechCursor=Math.max(speechCursor,Math.min(found,speechCursor+80));speechCursorFloat=Math.max(speechCursorFloat,speechCursor);lastSpeechMatchAt=Date.now();setTeleProgress(speechCursor);$('#listenState').textContent=`已跟随到第 ${speechCursor} 字`;return matched>=2}
async function startSmartTele(){clearInterval(teleTimer);if(speechRestartTimer)clearTimeout(speechRestartTimer);if(speechRecognition)try{speechRecognition.onend=null;speechRecognition.stop()}catch(e){}speechRecognitionBlocked=false;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#listenState').textContent='当前浏览器不支持逐字识别，请使用最新版 Chrome';return}let stream;try{stream=await ensureMicrophone();startNeuralVad(stream).catch(()=>{})}catch(e){$('#listenState').textContent='麦克风不可用，请检查权限';return}speechRecognition=new SR();speechRecognition.lang='zh-CN';speechRecognition.continuous=true;speechRecognition.interimResults=true;speechRecognition.maxAlternatives=1;speechRecognition.onstart=()=>{$('#listenState').textContent='逐字识别已开启，请开始朗读'};speechRecognition.onresult=e=>{lastVoiceAt=Date.now();let transcript='';for(let i=0;i<e.results.length;i++)transcript+=e.results[i][0]?.transcript||'';if(!followRecognizedText(transcript.slice(-96)))$('#listenState').textContent='正在听，等待匹配讲稿'};speechRecognition.onerror=e=>{speechRecognitionBlocked=['not-allowed','service-not-allowed','audio-capture'].includes(e.error);$('#listenState').textContent=e.error==='not-allowed'||e.error==='service-not-allowed'?'请允许浏览器使用语音识别':e.error==='audio-capture'?'未检测到麦克风':'语音识别正在重连'};speechRecognition.onend=()=>{if(!speechRecognitionBlocked&&$('#teleprompter').classList.contains('show')&&smartTele&&!telePaused)speechRestartTimer=setTimeout(()=>{try{speechRecognition.start()}catch(e){}},500)};try{speechRecognition.start()}catch(e){$('#listenState').textContent='语音识别启动失败，请重新开启提词器'}}
$('#script').value=localStorage.getItem('rhino-tele-script')||'';$('#smartTeleToggle').onclick=()=>{smartTele=!smartTele;$('#smartTeleToggle').classList.toggle('active',smartTele);$('#listenState').textContent=smartTele?'逐字跟随':'匀速模式';if(smartTele&&$('#teleprompter').classList.contains('show'))startSmartTele();else if(!smartTele){clearInterval(teleTimer);if(speechRecognition)try{speechRecognition.stop()}catch(e){}}};$('#fontSize').oninput=e=>{$('#fontOut').value=e.target.value;updateTele()};$('#teleSpeed').oninput=e=>$('#speedOut').value=e.target.value;$('#startTele').onclick=()=>{updateTele();$('#teleprompter').classList.add('show');$('#scriptPanel').classList.remove('open');telePaused=false;if(captureSession)requestAnimationFrame(sizeCaptureStage);if(smartTele)startSmartTele();else startTeleScroll();showToast('提词器已启动')};function startTeleScroll(){clearInterval(teleTimer);teleTimer=setInterval(()=>{if(!telePaused){const t=$('#teleText'),y=+(t.dataset.y||0)-Number($('#teleSpeed').value)/3;t.dataset.y=y;t.style.transform=`translateY(${y}px)`}},30)}$('#pauseTele').onclick=()=>{telePaused=!telePaused;$('#pauseTele').textContent=telePaused?'▶':'Ⅱ';$('#listenState').textContent=telePaused?'已暂停':'正在聆听';if(telePaused&&speechRecognition)try{speechRecognition.stop()}catch(e){}else if(!telePaused&&smartTele)startSmartTele()};function closeTele(){clearInterval(teleTimer);if(speechRestartTimer)clearTimeout(speechRestartTimer);speechRestartTimer=null;if(speechRecognition)try{speechRecognition.stop()}catch(e){}speechRecognition=null;if(neuralVad)Promise.resolve(neuralVad.pause()).catch(()=>{});neuralSpeaking=false;$('#teleprompter').classList.remove('show');if(captureSession)requestAnimationFrame(sizeCaptureStage);$('#teleText').style.transform='';$('#teleText').dataset.y=0;$('#listenState').textContent='待机'}$('#closeTele').onclick=closeTele;$('#hideTele').onclick=closeTele;
function parseRatio(value){const parts=String(value).split('/').map(Number);return parts.length===2&&parts[0]>0&&parts[1]>0?parts[0]/parts[1]:16/9}
function sizeCaptureStage(){if(!captureSession)return;const teleVisible=$('#teleprompter').classList.contains('show'),r=parseRatio(ratio),pad=Math.min(capturePadding,60);let maxW=innerWidth-pad*2,maxH=innerHeight-pad*2;if(teleVisible){maxW=Math.min(maxW,innerWidth*.72);maxH=Math.min(maxH,innerHeight*.62)}let width=maxW,height=width/r;if(height>maxH){height=maxH;width=height*r}captureSession.stage.style.top='50%';captureSession.stage.style.left='50%';captureSession.stage.style.transform='translate(-50%,-50%)';captureSession.stage.style.width=Math.round(width)+'px';captureSession.stage.style.height=Math.round(height)+'px';captureSession.stage.style.padding=pad+'px';requestAnimationFrame(()=>{fitCanvas(current());keepTeleOutsideCapture()})}
function styleCapturedFrame(frame){frame.style.width='100%';frame.style.height='auto';frame.style.maxWidth='100%';frame.style.maxHeight='100%';frame.style.aspectRatio=ratio}
function switchCaptureSlide(i){if(!captureSession)return;const next=slides[i].canvas.closest('.slide-frame'),old=captureSession.records[0];if(!next||old.node===next)return;old.marker.replaceWith(old.node);if(old.style===null)old.node.removeAttribute('style');else old.node.setAttribute('style',old.style);const marker=document.createComment('capture-slide-placeholder');next.parentNode.insertBefore(marker,next);captureSession.records[0]={node:next,marker,style:next.getAttribute('style')};captureSession.stage.insertBefore(next,captureSession.stage.firstChild);styleCapturedFrame(next);requestAnimationFrame(()=>fitCanvas(slides[i]))}
function prepareCaptureStage(){if(captureSession)return captureSession.stage;const frame=current().card.querySelector('.slide-frame'),stage=document.createElement('section'),nodes=[frame,cam],records=nodes.map(node=>{const marker=document.createComment('capture-placeholder');node.parentNode.insertBefore(marker,node);return{node,marker,style:node.getAttribute('style')}});stage.id='captureStage';stage.className='capture-stage';stage.style.background=$('#recordPreview').style.background||'linear-gradient(135deg,#ffd6e7,#d7ffd2,#d8d7ff)';$('#studio').appendChild(stage);records.forEach(({node})=>stage.appendChild(node));frame.style.width='100%';frame.style.height='auto';frame.style.maxWidth='100%';frame.style.maxHeight='100%';frame.style.aspectRatio=ratio;cam.style.left='auto';cam.style.right='24px';cam.style.top='auto';cam.style.bottom='24px';cam.style.transform='scaleX(-1)';captureSession={stage,records};$('#studio').classList.add('capture-preview');sizeCaptureStage();return stage}
function restoreCaptureStage(){if(!captureSession)return;const session=captureSession;captureSession=null;session.records.forEach(({node,marker,style})=>{marker.replaceWith(node);if(style===null)node.removeAttribute('style');else node.setAttribute('style',style)});session.stage.remove();$('#studio').classList.remove('capture-preview');requestAnimationFrame(()=>slides.forEach(fitCanvas))}
function resetRecordButton(){clearInterval(recordTimer);const b=$('#recordBtn');b.classList.remove('recording','armed');b.innerHTML='<span class="rec-dot"></span>录制';$('#studio').classList.remove('recording-active');const cancel=$('#cancelRecord');if(cancel)cancel.remove();restoreCaptureStage()}
async function stopRecording(){if(recorder&&recorder.state!=='inactive'){try{recorder.requestData()}catch(e){}recorder.stop()}}
function loadExternalScript(src){return new Promise((resolve,reject)=>{const existing=document.querySelector(`script[src="${src}"]`);if(existing){if(window.FFmpeg)resolve();else existing.addEventListener('load',resolve,{once:true});return}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('MP4 转码组件加载失败'));document.head.appendChild(s)})}
async function convertToMp4(blob){setDeviceStatus('ready','正在本地转换为 MP4，请稍候…');const lib='https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js';await loadExternalScript(lib);if(!window.FFmpeg?.createFFmpeg)throw new Error('MP4 转码组件不可用');const ffmpeg=window.FFmpeg.createFFmpeg({log:false,corePath:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js'});await ffmpeg.load();ffmpeg.FS('writeFile','input.webm',await window.FFmpeg.fetchFile(blob));await ffmpeg.run('-i','input.webm','-c:v','libx264','-preset','veryfast','-crf','22','-c:a','aac','-movflags','faststart','output.mp4');const data=ffmpeg.FS('readFile','output.mp4');ffmpeg.exit();return new Blob([data.buffer],{type:'video/mp4'})}
function outputDimensions(){const map={'16/9':[1920,1080],'4/3':[1440,1080],'3/4':[1080,1440],'9/16':[1080,1920],'1/1':[1080,1080]};if(map[ratio])return map[ratio];const r=parseRatio(ratio);return r>=1?[1440,Math.round(1440/r)]:[Math.round(1440*r),1440]}
function drawWatermark(cx,width,height){const label='RHINO · WHITEBOARD',fontSize=Math.max(12,Math.round(Math.min(width,height)*.012)),padX=Math.round(fontSize*.65),padY=Math.round(fontSize*.38),margin=Math.round(width*.014);cx.save();cx.font=`600 ${fontSize}px -apple-system,BlinkMacSystemFont,sans-serif`;const tw=cx.measureText(label).width,boxW=tw+padX*2,boxH=fontSize+padY*2,x=margin,y=height-boxH-margin;cx.globalAlpha=.28;cx.fillStyle='#101115';if(cx.roundRect){cx.beginPath();cx.roundRect(x,y,boxW,boxH,boxH/2);cx.fill()}else cx.fillRect(x,y,boxW,boxH);cx.globalAlpha=.58;cx.fillStyle='#fff';cx.textBaseline='middle';cx.fillText(label,x+padX,y+boxH/2);cx.restore()}
async function createVideoCompositor(track,crop=null){
  if(!HTMLCanvasElement.prototype.captureStream)return{track:track.clone(),cleanup:()=>{}};
  const [width,height]=outputDimensions(),video=document.createElement('video'),surface=document.createElement('canvas'),cx=surface.getContext('2d',{alpha:false});
  video.muted=true;video.playsInline=true;video.srcObject=new MediaStream([track]);video.style.display='none';surface.width=width;surface.height=height;surface.style.display='none';document.body.append(video,surface);await video.play();
  let stopped=false;const draw=()=>{if(stopped)return;const sw=video.videoWidth||width,sh=video.videoHeight||height;cx.fillStyle='#111217';cx.fillRect(0,0,width,height);if(recordMode==='studio'&&crop){const sx=Math.max(0,crop.x*sw/crop.viewportWidth),sy=Math.max(0,crop.y*sh/crop.viewportHeight),sWidth=Math.min(sw-sx,crop.width*sw/crop.viewportWidth),sHeight=Math.min(sh-sy,crop.height*sh/crop.viewportHeight);cx.drawImage(video,sx,sy,sWidth,sHeight,0,0,width,height)}else if(recordMode==='studio')cx.drawImage(video,0,0,width,height);else{const scale=recordMode==='camera'?Math.max(width/sw,height/sh):Math.min(width/sw,height/sh),dw=sw*scale,dh=sh*scale;cx.drawImage(video,(width-dw)/2,(height-dh)/2,dw,dh)}drawWatermark(cx,width,height);if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(draw);else requestAnimationFrame(draw)};
  draw();const stream=surface.captureStream(30),outTrack=stream.getVideoTracks()[0];return{track:outTrack,width,height,cleanup:()=>{stopped=true;outTrack.stop();video.pause();video.srcObject=null;video.remove();surface.remove()}}
}
/* === Recording flow with smooth UX === */
$('#recordBtn').onclick=async function(){
  if(recorder&&recorder.state==='recording'){await stopRecording();return}
  if(recordMode==='studio'&&!captureSession){const stage=prepareCaptureStage();this.classList.add('armed');this.innerHTML='<span class="rec-dot"></span>开始录制';const cancel=document.createElement('button');cancel.id='cancelRecord';cancel.className='cancel-record';cancel.textContent='× 取消';cancel.onclick=()=>resetRecordButton();this.parentNode.insertBefore(cancel,this);setDeviceStatus('ready',`已框定 ${ratio} 成片区域 · 边距 ${capturePadding}px`);showToast('录制区域已就绪，点击"开始录制"');return}
  if(!window.MediaRecorder||!navigator.mediaDevices?.getUserMedia){alert('当前浏览器不支持媒体录制，请使用最新版 Chrome、Edge 或 Safari。');return}
  if(recordMode!=='camera'&&!navigator.mediaDevices.getDisplayMedia){alert('当前浏览器不支持屏幕共享录制。你可以在设置中选择"仅摄像头"。');return}
  try{
    this.disabled=true;
    let source;
    if(recordMode==='camera')source=await ensureCamera();
    else{
      if($('#cameraToggle').classList.contains('active'))await ensureCamera();
      source=await ensureDisplayStream(recordMode);
      if(recordMode==='studio'){const surface=source.getVideoTracks()[0]?.getSettings?.().displaySurface;if(surface&&surface!=='browser'){source.getTracks().forEach(t=>t.stop());throw new Error('请在共享窗口中选择"当前犀牛白板标签页"，不要选择整个屏幕或窗口')}}
    }
    const mic=await ensureMicrophone().catch(()=>null),output=new MediaStream();
    const stageRect=recordMode==='studio'&&captureSession?captureSession.stage.getBoundingClientRect():null,crop=stageRect?{x:stageRect.x,y:stageRect.y,width:stageRect.width,height:stageRect.height,viewportWidth:innerWidth,viewportHeight:innerHeight}:null;
    videoCompositor=await createVideoCompositor(source.getVideoTracks()[0],crop);output.addTrack(videoCompositor.track);setDeviceStatus('ready',`输出画幅 ${videoCompositor.width}×${videoCompositor.height} · 仅绿色区域`);
    const audioTracks=[...(recordMode==='camera'?[]:source.getAudioTracks()),...(mic?mic.getAudioTracks():[])];recordTracks=[];
    if(audioTracks.length&&(window.AudioContext||window.webkitAudioContext)){const AC=window.AudioContext||window.webkitAudioContext;audioContext=new AC();const dest=audioContext.createMediaStreamDestination();audioTracks.forEach(t=>audioContext.createMediaStreamSource(new MediaStream([t])).connect(dest));dest.stream.getAudioTracks().forEach(t=>output.addTrack(t))}else if(audioTracks[0])output.addTrack(audioTracks[0]);
    const candidates=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4;codecs=h264,aac','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];const mime=candidates.find(t=>MediaRecorder.isTypeSupported(t))||'';
    recorder=new MediaRecorder(output,mime?{mimeType:mime,videoBitsPerSecond:6000000}:undefined);chunks=[];
    recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};
    recorder.onerror=e=>{console.error(e);setDeviceStatus('error','录制发生错误，请停止后重试')};
    recorder.onstop=async()=>{
      resetRecordButton();output.getTracks().forEach(t=>t.stop());recordTracks.forEach(t=>t.stop());recordTracks=[];if(videoCompositor){videoCompositor.cleanup();videoCompositor=null}
      if(audioContext){await audioContext.close().catch(()=>{});audioContext=null}
      if(!chunks.length){setDeviceStatus('error','没有生成有效录像');alert('没有生成有效录像，请确认摄像头或共享画面正常。');return}
      const type=recorder.mimeType||mime||'video/webm',isMp4=type.includes('mp4');let blob=new Blob(chunks,{type}),ext='mp4';
      if(!isMp4){try{blob=await convertToMp4(blob)}catch(error){console.error(error);ext='webm';setDeviceStatus('error','MP4 转换失败，已保留原始录像以免内容丢失')}}
      const url=URL.createObjectURL(blob),a=document.createElement('a');if(ext==='mp4')setDeviceStatus('ready','录制完成，MP4 已开始下载');
      a.href=url;a.download='rhino-whiteboard-'+new Date().toISOString().slice(0,19).replaceAll(':','-')+'.'+ext;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);showToast('录制完成，文件已下载')
    };
    if(captureSession)captureSession.stage.classList.add('live');$('#studio').classList.add('recording-active');recorder.start(1000);setDeviceStatus('ready',`正在录制 ${videoCompositor.width}×${videoCompositor.height} · ${mime.includes('mp4')?'MP4':'待转 MP4'}`);this.classList.add('recording');this.innerHTML='<span class="rec-dot"></span>00:00';
    const began=Date.now();recordTimer=setInterval(()=>{const sec=Math.floor((Date.now()-began)/1000),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');this.innerHTML=`<span class="rec-dot"></span>${m}:${s}`},1000);showToast('录制已开始')
  }catch(e){resetRecordButton();recordTracks.forEach(t=>t.stop());recordTracks=[];if(videoCompositor){videoCompositor.cleanup();videoCompositor=null}setDeviceStatus('error',e?.name==='NotAllowedError'?'权限被取消，请允许摄像头、麦克风或屏幕共享':'录制启动失败：'+(e?.message||'未知错误'));showToast('录制启动失败','error')}
  finally{this.disabled=false}
};
$('#homeBtn').onclick=()=>location.href='index.html#builds';$('#helpBtn').onclick=()=>$('#welcome').classList.remove('hide');const welcome=$('#welcome');function closeWelcome(){welcome.classList.add('hide');localStorage.setItem('rhino-whiteboard-v4','1')}$('#welcomeGo').onclick=closeWelcome;welcome.onclick=e=>e.target===welcome&&closeWelcome();
/* === Enhanced keyboard shortcuts === */
addEventListener('keydown',e=>{
  const editing=/INPUT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable;
  const map={1:'select',2:'rect',3:'diamond',4:'circle',5:'arrow',6:'line',7:'pen',8:'text',0:'eraser',h:'hand',H:'hand'};
  if(map[e.key]&&!editing)setTool(map[e.key]);
  // Undo/Redo
  if((e.metaKey||e.ctrlKey)&&e.key==='z'&&!editing){e.preventDefault();if(e.shiftKey)$('#redo').click();else $('#undo').click()}
  // Duplicate
  if((e.metaKey||e.ctrlKey)&&e.key==='d'&&!editing){e.preventDefault();const el=$('.media-item.selected');if(el){const clone=el.cloneNode(true);clone.style.left=(parseInt(el.style.left||0)+20)+'px';clone.style.top=(parseInt(el.style.top||0)+20)+'px';mediaLayerOf().appendChild(clone);makeMediaInteractive(clone);showToast('已复制')}}
  // Delete
  if((e.key==='Delete'||e.key==='Backspace')&&!editing){const selected=$('.media-item.selected');if(selected){e.preventDefault();selected.remove();showToast('对象已删除')}}
  // Export
  if((e.metaKey||e.ctrlKey)&&e.key==='e'&&!editing){e.preventDefault();$('#exportBtn').click()}
  // Space → temporary hand
  if(e.key===' '&&!editing&&tool!=='hand'){e.preventDefault();workspace.classList.add('hand')}
  // Zoom
  if((e.metaKey||e.ctrlKey)&&e.key==='='&&!editing){e.preventDefault();setZoom(zoom+5)}
  if((e.metaKey||e.ctrlKey)&&e.key==='-'&&!editing){e.preventDefault();setZoom(zoom-5)}
  if((e.metaKey||e.ctrlKey)&&e.key==='0'&&!editing){e.preventDefault();setZoom(20)}
  // Escape
  if(e.key==='Escape'){closeWelcome();$('.media-item.selected')?.classList.remove('selected');$$('.panel').forEach(p=>p.classList.remove('open'));$('#moreMenu').classList.remove('open');$('#stylePanel').classList.remove('open')}
});
// Release space → restore previous tool
addEventListener('keyup',e=>{if(e.key===' '&&tool!=='hand'&&!/INPUT|TEXTAREA/.test(e.target.tagName)){workspace.classList.remove('hand')}});
if(localStorage.getItem('rhino-whiteboard-v4')||localStorage.getItem('rhino-whiteboard-v3'))welcome.classList.add('hide');
workspace.addEventListener('click',e=>{const card=e.target.closest('.slide-card');if(!card)return;card.classList.remove('click-focus');requestAnimationFrame(()=>card.classList.add('click-focus'));setTimeout(()=>card.classList.remove('click-focus'),750)});
addEventListener('keydown',e=>{if(captureSession&&!/INPUT|TEXTAREA/.test(e.target.tagName)&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();selectSlide(Math.max(0,Math.min(slides.length-1,active+(e.key==='ArrowRight'?1:-1))),false)}if(!recorder||recorder.state!=='recording'||/INPUT|TEXTAREA/.test(e.target.tagName))return;const parts=[];if(e.metaKey)parts.push('⌘');if(e.ctrlKey)parts.push('Ctrl');if(e.altKey)parts.push('⌥');if(e.shiftKey)parts.push('⇧');if(!['Meta','Control','Alt','Shift'].includes(e.key))parts.push(e.key.length===1?e.key.toUpperCase():e.key);if(!parts.length)return;const badge=document.createElement('div');badge.className='key-badge';badge.textContent=parts.join(' + ');document.body.appendChild(badge);setTimeout(()=>badge.remove(),1400)});
slides=[makeSlide(),makeSlide()];renderAll();selectSlide(0,false);setZoom(20);addEventListener('resize',()=>slides.forEach(fitCanvas));
})();
