(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],workspace=$('#workspace'),row=$('#slideRow'),thumbs=$('#slideThumbs');
let slides=[],active=0,tool='select',locked=false,zoom=20,ratio='16/9',cameraStream=null,recorder=null,chunks=[],teleTimer=null,telePaused=false,dragPan=null;
const uid=()=>Math.random().toString(36).slice(2,9),current=()=>slides[active],canvas=()=>current().canvas,ctx=()=>current().ctx;
function makeSlide(){return{id:uid(),canvas:null,ctx:null,card:null,undo:[],redo:[],bg:'#fff',template:'',media:[]}}
function buildSlide(slide,index){const card=document.createElement('article');card.className='slide-card'+(index===active?' selected':'');card.dataset.index=index;card.innerHTML=`<label>Slide ${index+1}</label><div class="slide-frame"><div class="template-layer"></div><div class="media-layer"></div><canvas class="draw-canvas"></canvas><div class="empty-hint"><div><b>Slide ${index+1}</b>选择工具开始创作</div></div></div>`;row.appendChild(card);slide.card=card;slide.canvas=card.querySelector('canvas');slide.ctx=slide.canvas.getContext('2d');fitCanvas(slide);attachCanvas(slide);card.addEventListener('pointerdown',()=>selectSlide(index,false));}
function fitCanvas(s){const c=s.canvas,w=c.clientWidth,h=c.clientHeight,old=c.width?c.toDataURL():null;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;s.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);s.ctx.lineCap='round';s.ctx.lineJoin='round';if(old){const im=new Image;im.onload=()=>s.ctx.drawImage(im,0,0,w,h);im.src=old}}
function renderAll(){row.innerHTML='';slides.forEach(buildSlide);renderThumbs();requestAnimationFrame(()=>slides.forEach(fitCanvas))}
function renderThumbs(){thumbs.innerHTML='';slides.forEach((s,i)=>{const b=document.createElement('button');b.className='thumb'+(i===active?' active':'');b.textContent=i+1;b.title=`切换到幻灯片 ${i+1}`;b.onclick=()=>selectSlide(i,true);thumbs.appendChild(b)})}
function selectSlide(i,scroll=true){active=i;$$('.slide-card').forEach((c,n)=>c.classList.toggle('selected',n===i));$$('.thumb').forEach((b,n)=>b.classList.toggle('active',n===i));if(scroll)slides[i].card.scrollIntoView({behavior:'smooth',block:'center',inline:'center'})}
function snapshot(s=current()){return s.canvas.toDataURL()}function push(s=current()){s.undo.push(snapshot(s));if(s.undo.length>50)s.undo.shift();s.redo=[];s.card.querySelector('.empty-hint').style.display='none'}
function restore(s,url){s.ctx.clearRect(0,0,s.canvas.width,s.canvas.height);if(!url)return;const im=new Image;im.onload=()=>s.ctx.drawImage(im,0,0,s.canvas.clientWidth,s.canvas.clientHeight);im.src=url}
function point(e,c){const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function attachCanvas(s){let drawing=false,start=null,before=null;const c=s.canvas,x=s.ctx;c.onpointerdown=e=>{if(tool==='select'||tool==='hand')return;e.preventDefault();selectSlide(slides.indexOf(s),false);start=point(e,c);before=snapshot(s);if(tool==='text'){const text=prompt('输入文字');if(text){push(s);x.fillStyle='#202124';x.font='28px Georgia,serif';x.fillText(text,start.x,start.y)}return}push(s);drawing=true;x.strokeStyle='#1f1f22';x.lineWidth=tool==='eraser'?22:3;x.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';if(tool==='pen'||tool==='eraser'){x.beginPath();x.moveTo(start.x,start.y);c.setPointerCapture(e.pointerId)}};c.onpointermove=e=>{if(!drawing)return;const p=point(e,c);if(tool==='pen'||tool==='eraser'){x.lineTo(p.x,p.y);x.stroke();return}restore(s,before);setTimeout(()=>drawShape(x,start,p,tool),0)};c.onpointerup=()=>{drawing=false;x.globalCompositeOperation='source-over'} }
function drawShape(x,a,b,t){x.strokeStyle='#1f1f22';x.lineWidth=3;x.beginPath();if(t==='line'||t==='arrow'){x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);if(t==='arrow'){const q=Math.atan2(b.y-a.y,b.x-a.x),l=14;x.lineTo(b.x-l*Math.cos(q-.5),b.y-l*Math.sin(q-.5));x.moveTo(b.x,b.y);x.lineTo(b.x-l*Math.cos(q+.5),b.y-l*Math.sin(q+.5))}}if(t==='rect')x.rect(a.x,a.y,b.x-a.x,b.y-a.y);if(t==='circle'){const rx=(b.x-a.x)/2,ry=(b.y-a.y)/2;x.ellipse(a.x+rx,a.y+ry,Math.abs(rx),Math.abs(ry),0,0,Math.PI*2)}if(t==='diamond'){x.moveTo((a.x+b.x)/2,a.y);x.lineTo(b.x,(a.y+b.y)/2);x.lineTo((a.x+b.x)/2,b.y);x.lineTo(a.x,(a.y+b.y)/2);x.closePath()}x.stroke()}
function setTool(t){tool=t;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));workspace.classList.toggle('hand',t==='hand')}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#lockBtn').onclick=()=>{locked=!locked;$('#lockBtn').classList.toggle('locked',locked)};
$('#addSlide').onclick=()=>{const s=makeSlide();slides.push(s);buildSlide(s,slides.length-1);renderThumbs();selectSlide(slides.length-1,true)};$('#undo').onclick=()=>{const s=current();if(!s.undo.length)return;s.redo.push(snapshot(s));restore(s,s.undo.pop())};$('#redo').onclick=()=>{const s=current();if(!s.redo.length)return;s.undo.push(snapshot(s));restore(s,s.redo.pop())};
workspace.onpointerdown=e=>{if(tool!=='hand')return;dragPan={x:e.clientX,y:e.clientY,l:workspace.scrollLeft,t:workspace.scrollTop};workspace.classList.add('dragging')};workspace.onpointermove=e=>{if(!dragPan)return;workspace.scrollLeft=dragPan.l-(e.clientX-dragPan.x);workspace.scrollTop=dragPan.t-(e.clientY-dragPan.y)};workspace.onpointerup=()=>{dragPan=null;workspace.classList.remove('dragging')};
function setZoom(n){zoom=Math.max(10,Math.min(100,n));row.style.transform=`scale(${zoom/20})`;row.style.transformOrigin='top left';$('#zoomValue').textContent=zoom+'%'}$('#zoomOut').onclick=()=>setZoom(zoom-5);$('#zoomIn').onclick=()=>setZoom(zoom+5);
$('#moreBtn').onclick=e=>{e.stopPropagation();$('#moreMenu').classList.toggle('open')};document.addEventListener('click',e=>{if(!e.target.closest('#moreMenu')&&!e.target.closest('#moreBtn'))$('#moreMenu').classList.remove('open')});
function insertFile(kind,file){const s=current(),url=URL.createObjectURL(file),el=document.createElement(kind==='image'?'img':'video');el.src=url;el.className='media-item';if(kind==='video'){el.controls=true;el.playsInline=true}s.card.querySelector('.media-layer').appendChild(el);makeMediaInteractive(el);s.media.push({kind,url});s.card.querySelector('.empty-hint').style.display='none'}
function makeMediaInteractive(el){el.onclick=e=>{e.stopPropagation();$$('.media-item').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')};let d=null;el.onpointerdown=e=>{if(tool!=='select')return;d={x:e.clientX,y:e.clientY,l:el.offsetLeft,t:el.offsetTop};el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!d)return;el.style.left=d.l+e.clientX-d.x+'px';el.style.top=d.t+e.clientY-d.y+'px';el.style.transform='none'};el.onpointerup=()=>d=null}
$('#imageInput').onchange=e=>e.target.files[0]&&insertFile('image',e.target.files[0]);$('#videoInput').onchange=e=>e.target.files[0]&&insertFile('video',e.target.files[0]);$('#imageTool').onclick=()=>$('#imageInput').click();
$$('[data-insert]').forEach(b=>b.onclick=()=>{const k=b.dataset.insert;$('#moreMenu').classList.remove('open');if(k==='image')$('#imageInput').click();if(k==='video')$('#videoInput').click();if(k==='template')openPanel('templatePanel');if(k==='web'){const u=prompt('输入要嵌入的网页地址（需支持 iframe）：','https://');if(!u)return;const f=document.createElement('iframe');f.src=u;f.className='media-item web';f.setAttribute('sandbox','allow-scripts allow-same-origin allow-forms allow-popups');current().card.querySelector('.media-layer').appendChild(f);makeMediaInteractive(f);current().card.querySelector('.empty-hint').style.display='none'}});
function openPanel(id){$$('.panel').forEach(p=>p.classList.toggle('open',p.id===id))}$('#settingsBtn').onclick=()=>openPanel('settingsPanel');$('#scriptBtn').onclick=()=>openPanel('scriptPanel');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));
$$('.ratio').forEach(b=>b.onclick=()=>{ratio=b.dataset.ratio;$$('.ratio').forEach(x=>x.classList.toggle('active',x===b));$$('.slide-frame').forEach(f=>f.style.aspectRatio=ratio);setTimeout(()=>slides.forEach(fitCanvas),80)});$$('[data-bg]').forEach(b=>b.onclick=()=>{const s=current();s.bg=b.dataset.bg;s.card.querySelector('.slide-frame').style.background=b.dataset.bg});
const templates={title:`<div style="height:100%;padding:11%;background:linear-gradient(135deg,#fff8ef,#edf4ff);display:flex;flex-direction:column;justify-content:center"><small style="letter-spacing:.2em;color:#806f60">RHINO STUDIO</small><h1 style="font:700 48px Georgia;margin:12px 0">在此输入标题</h1><p style="font-size:20px;color:#777">用一句话说明你的核心观点</p></div>`,lesson:`<div style="height:100%;display:grid;grid-template-columns:30% 1fr"><div style="background:#20242d;color:#fff;padding:14%"><b>01</b><h2 style="font:32px Georgia">课程主题</h2></div><div style="padding:9%"><h1>今天我们讲什么？</h1><p style="color:#777;font-size:18px">在右侧画布逐步拆解你的内容</p></div></div>`,points:`<div style="height:100%;padding:8%;background:#fcfaf5"><h1 style="font:38px Georgia">三个关键要点</h1><div style="display:flex;gap:4%;margin-top:8%">${[1,2,3].map(n=>`<div style="flex:1;padding:5%;background:#fff;border-radius:12px"><b>0${n}</b><h2>要点 ${n}</h2><p style="color:#888">补充说明</p></div>`).join('')}</div></div>`,dark:`<div style="height:100%;padding:10%;color:#fff;background:radial-gradient(circle at 75% 25%,#4b59c4,#111521 58%)"><small style="color:#aab2ff">NEW IDEA</small><h1 style="font:700 52px Georgia;max-width:70%">让想法被看见</h1><p style="font-size:20px;color:#c7cae8">犀牛白板 · 创作发布会</p></div>`};$$('[data-template]').forEach(b=>b.onclick=()=>{const s=current();s.template=b.dataset.template;s.card.querySelector('.template-layer').innerHTML=templates[s.template];s.card.querySelector('.empty-hint').style.display='none';$('#templatePanel').classList.remove('open')});
const cam=$('#camera');$('#cameraBtn').onclick=async()=>{if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;cam.classList.remove('show');$('#cameraBtn').textContent='开启摄像头';return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});cam.srcObject=cameraStream;cam.classList.add('show');$('#cameraBtn').textContent='关闭摄像头'}catch(e){alert('无法访问摄像头，请检查浏览器权限。')}};
function updateTele(){const text=$('#script').value.trim()||'请先输入讲稿';$('#teleText').textContent=text;$('#teleText').style.fontSize=$('#fontSize').value+'px';localStorage.setItem('rhino-tele-script',$('#script').value)}$('#script').value=localStorage.getItem('rhino-tele-script')||'';$('#fontSize').oninput=e=>{$('#fontOut').value=e.target.value;updateTele()};$('#teleSpeed').oninput=e=>$('#speedOut').value=e.target.value;$('#startTele').onclick=()=>{updateTele();$('#teleprompter').classList.add('show');$('#scriptPanel').classList.remove('open');telePaused=false;startTeleScroll()};function startTeleScroll(){clearInterval(teleTimer);teleTimer=setInterval(()=>{if(!telePaused){const t=$('#teleText'),y=+(t.dataset.y||0)-Number($('#teleSpeed').value)/3;t.dataset.y=y;t.style.transform=`translateY(${y}px)`}},30)}$('#pauseTele').onclick=()=>{telePaused=!telePaused;$('#pauseTele').textContent=telePaused?'▶':'Ⅱ'};function closeTele(){clearInterval(teleTimer);$('#teleprompter').classList.remove('show');$('#teleText').style.transform='';$('#teleText').dataset.y=0}$('#closeTele').onclick=closeTele;$('#hideTele').onclick=closeTele;
$('#recordBtn').onclick=async function(){if(recorder&&recorder.state==='recording'){recorder.stop();this.classList.remove('recording');this.innerHTML='<b></b>录制';return}try{const screen=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}),mic=await navigator.mediaDevices.getUserMedia({audio:true}).catch(()=>null),tracks=[...screen.getVideoTracks(),...screen.getAudioTracks(),...(mic?mic.getAudioTracks():[])];recorder=new MediaRecorder(new MediaStream(tracks));chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{tracks.forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='rhino-whiteboard-'+new Date().toISOString().slice(0,19).replaceAll(':','-')+'.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};screen.getVideoTracks()[0].onended=()=>recorder.state==='recording'&&recorder.stop();recorder.start(1000);this.classList.add('recording');this.textContent='■ 停止'}catch(e){alert('录制未开始。请选择分享屏幕并允许麦克风。')}};
$('#homeBtn').onclick=()=>location.href='index.html#builds';$('#helpBtn').onclick=()=>$('#welcome').classList.remove('hide');const welcome=$('#welcome');function closeWelcome(){welcome.classList.add('hide');localStorage.setItem('rhino-whiteboard-v3','1')}$('#welcomeGo').onclick=closeWelcome;welcome.onclick=e=>e.target===welcome&&closeWelcome();addEventListener('keydown',e=>{const map={1:'select',2:'rect',3:'diamond',4:'circle',5:'arrow',6:'line',7:'pen',8:'text',0:'eraser',h:'hand',H:'hand'};if(map[e.key]&&!/INPUT|TEXTAREA/.test(e.target.tagName))setTool(map[e.key]);if(e.key==='Escape'){closeWelcome();$$('.panel').forEach(p=>p.classList.remove('open'));$('#moreMenu').classList.remove('open')}});if(localStorage.getItem('rhino-whiteboard-v3'))welcome.classList.add('hide');
slides=[makeSlide(),makeSlide()];renderAll();selectSlide(0,false);setZoom(20);addEventListener('resize',()=>slides.forEach(fitCanvas));
})();
